Fawry CardToken APIs
fawry-api/fawry pull request #11
Opened 2020-12-03 08:18 UTC by AhmedAliIbrahim

This PR enables using Fawry List, create and delete Card Token

2020-12-03 11:35 UTC, amrrbakry commented
Hi @AhmedAliIbrahim,

thank you so much for this valuable contribution 💯 👍 Could you please take a look at the rubocop offenses in circleci and fix them? You can disable the offenses around the `build_request` method as I think it doesn't make much sense to change it. 

Also, could you add your change to the README.md and README-ar.md? Thanks!

I will review again ASAP.

2020-12-03 12:42 UTC, AhmedAliIbrahim commented
Hello @amrrbakry,
I'll update the README file ASAP

2020-12-03 19:09 UTC, amrrbakry requested changes
LGTM. Please add the unit tests and fix the rubocop offenses (ignore the ones around the `build_request` method), so I can merge. If you need any help, please let me know

2020-12-03 19:09 UTC, amrrbakry commented on lib/fawry/requests/charge_request.rb
> +      DEFAULTS = { payment_method: 'CARD', currency_code: 'EGP' }.freeze
I don't think this should be `CARD` by default, but you can provide it as param for card payments

2020-12-05 13:37 UTC, AhmedAliIbrahim commented
Hi @amrrbakry, I've updated Specs & README

2020-12-05 22:03 UTC, amrrbakry approved these changes

2020-12-05 22:04 UTC, amrrbakry commented
@AhmedAliIbrahim Thank you so much for this great contribution! 🎉 👍

2020-12-05 22:05 UTC, merged

2020-12-07 15:34 UTC, amrrbakry commented
published as Fawry `v.1.1.1` 🚀 Thanks for contributing 👍

2020-12-07 18:17 UTC, AhmedAliIbrahim commented
You're welcome 👍